# Generated by Django 5.1.2 on 2025-02-25 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal_details',
            name='DateOfBirth',
            field=models.DateField(),
        ),
    ]
