# Generated by Django 5.1.2 on 2025-02-25 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_alter_personal_details_dateofbirth'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visa_Travel_LanguagesKnown_FamilyInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HaveAVisa', models.CharField(max_length=120)),
                ('AreYouOpenToTravelToUSAOrSrilanka', models.CharField(max_length=120)),
                ('LanguageName', models.CharField(max_length=100)),
                ('CanRead', models.BooleanField(default=False)),
                ('CanWrite', models.BooleanField(default=False)),
                ('CanSpeak', models.BooleanField(default=False)),
                ('FamilyMemberName', models.CharField(max_length=100)),
                ('Relationship', models.CharField(max_length=50)),
                ('DateOfBirth', models.DateField()),
                ('Age', models.IntegerField()),
            ],
        ),
    ]
