# Generated by Django 5.1.2 on 2025-02-25 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0003_visa_travel_languagesknown_familyinformation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visa_travel_languagesknown_familyinformation',
            name='Age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='visa_travel_languagesknown_familyinformation',
            name='DateOfBirth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
