# Generated by Django 5.1.2 on 2025-02-26 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0004_alter_visa_travel_languagesknown_familyinformation_age_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalQualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Programe', models.CharField(max_length=255)),
                ('Institute', models.CharField(max_length=255)),
                ('Duration', models.DateField()),
                ('Percentage', models.CharField(max_length=10)),
                ('Division', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MajorAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Description', models.TextField()),
                ('Year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ProjectInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=255)),
                ('Company', models.CharField(max_length=255)),
                ('Client', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SeminarTraining',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SeminarTrainingProgram', models.CharField(max_length=255)),
                ('ConductedBy', models.CharField(max_length=255)),
                ('Duration', models.DateField()),
            ],
        ),
    ]
