# Generated by Django 5.1.2 on 2025-02-26 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0005_additionalqualification_majorachievement_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FriendRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FrndName1', models.CharField(max_length=255)),
                ('FrndCompany1', models.CharField(max_length=255)),
                ('FrndEmail1', models.EmailField(max_length=254)),
                ('FrndNbr1', models.CharField(max_length=20)),
                ('FrndName2', models.CharField(max_length=255)),
                ('FrndCompany2', models.CharField(max_length=255)),
                ('FrndEmail2', models.EmailField(max_length=254)),
                ('FrndNbr2', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PreviousEmployment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CompanyName', models.CharField(max_length=255)),
                ('LastDesignationHeld', models.CharField(max_length=255)),
                ('Address', models.TextField()),
                ('Telephone', models.CharField(max_length=20)),
                ('EmploymentPeriod', models.DateField()),
                ('EmployeeCode', models.CharField(max_length=50)),
                ('HRName', models.CharField(max_length=255)),
                ('HRContactNo', models.CharField(max_length=20)),
                ('ReportingManagerDesignation', models.CharField(max_length=255)),
                ('ReportingManagerContactNo', models.CharField(max_length=20)),
                ('AlternativeReportingManagerName', models.CharField(max_length=255)),
                ('AlternativeReportingManagerContactNo', models.CharField(max_length=20)),
                ('AlternativeReportingManagerDesignation', models.CharField(max_length=255)),
                ('AlternativeReportingManagerEmail', models.EmailField(max_length=254)),
                ('EmploymentNature', models.CharField(choices=[('Permanent', 'Permanent'), ('Temporary', 'Temporary')], max_length=20)),
                ('AgencyDetails', models.TextField(blank=True, null=True)),
                ('Remuneration', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ReasonForLeaving', models.TextField()),
            ],
        ),
    ]
