# Generated by Django 5.1.2 on 2025-02-26 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0006_friendrecommendation_previousemployment'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreviousEmployerDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Company2', models.CharField(max_length=255)),
                ('LastDesignationHeld2', models.CharField(max_length=255)),
                ('AddressMainOfficeAndBranch2', models.CharField(max_length=255)),
                ('Telephone2', models.CharField(max_length=15)),
                ('EmploymentPeriod2', models.DateField()),
                ('EmployeeCodePersonalNo2', models.CharField(max_length=50)),
                ('NameOfHR2', models.CharField(max_length=255)),
                ('ContactNoOfHR2', models.CharField(max_length=15)),
                ('DesignationDepartmentOfReportingManager2', models.CharField(max_length=255)),
                ('ContactNoOfReportingManager2', models.CharField(max_length=15)),
                ('NameOfAlternativeReportingManager2', models.CharField(max_length=255)),
                ('ContactNoOfAlternativeReportingManager2', models.CharField(max_length=15)),
                ('DesignationDepartmentOfAlternativeReportingManager2', models.CharField(max_length=255)),
                ('EmailIdOfAlternativeReportingManager2', models.EmailField(max_length=254)),
                ('WhetherEmploymentIsPermanentOrTemporary2', models.CharField(choices=[('Permanent', 'Permanent'), ('Temporary', 'Temporary')], max_length=10)),
                ('AgencyDetails2', models.TextField()),
                ('Remuneration2', models.DecimalField(decimal_places=2, max_digits=15)),
                ('ReasonForLeaving2', models.TextField()),
            ],
        ),
    ]
