# Generated by Django 5.1.2 on 2025-02-26 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0007_previousemployerdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreviousEmployersDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Company3', models.CharField(max_length=255)),
                ('LastDesignationHeld3', models.CharField(max_length=255)),
                ('AddressMainOfficeAndBranch3', models.CharField(max_length=255)),
                ('Telephone3', models.CharField(max_length=15)),
                ('EmploymentPeriod3', models.DateField()),
                ('EmployeeCodePersonalNo3', models.CharField(max_length=50)),
                ('NameOfHR3', models.CharField(max_length=255)),
                ('ContactNoOfHR3', models.CharField(max_length=15)),
                ('DesignationDepartmentOfReportingManager3', models.CharField(max_length=255)),
                ('ContactNoOfReportingManager3', models.CharField(max_length=15)),
                ('NameOfAlternativeReportingManager3', models.CharField(max_length=255)),
                ('ContactNoOfAlternativeReportingManager3', models.CharField(max_length=15)),
                ('DesignationDepartmentOfAlternativeReportingManager3', models.CharField(max_length=255)),
                ('EmailIdOfAlternativeReportingManager3', models.EmailField(max_length=254)),
                ('WhetherEmploymentIsPermanentOrTemporary3', models.CharField(choices=[('Permanent', 'Permanent'), ('Temporary', 'Temporary')], max_length=10)),
                ('AgencyDetails3', models.TextField()),
                ('Remuneration3', models.DecimalField(decimal_places=2, max_digits=15)),
                ('ReasonForLeaving3', models.TextField()),
            ],
        ),
    ]
