# Generated by Django 5.1.2 on 2025-02-26 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0008_previousemployersdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='previousemployersdetails',
            name='EmailIdOfAlternativeReportingManager3',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
