# Generated by Django 5.1.2 on 2025-02-26 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0010_gapsineducationandkeyresponsibilitiescurrentassignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Strength1', models.TextField()),
                ('Strength2', models.TextField()),
                ('Strength3', models.TextField()),
                ('Strength4', models.TextField()),
                ('Strength5', models.TextField()),
                ('Weakness1', models.TextField()),
                ('Weakness2', models.TextField()),
                ('Weakness3', models.TextField()),
                ('Weakness4', models.TextField()),
                ('Weakness5', models.TextField()),
                ('Referee1_Name', models.TextField()),
                ('Referee1_Company', models.TextField()),
                ('Referee1_Address', models.TextField()),
                ('Referee1_Contact', models.TextField()),
                ('Referee1_YearsAcquaintance', models.TextField()),
                ('Referee2_Name', models.TextField()),
                ('Referee2_Company', models.TextField()),
                ('Referee2_Address', models.TextField()),
                ('Referee2_Contact', models.TextField()),
                ('Referee2_YearsAcquaintance', models.TextField()),
                ('SportHobby_Why', models.TextField()),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
                ('UpdatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
