# Generated by Django 5.1.2 on 2025-03-18 06:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Company', models.CharField(max_length=255)),
                ('Position', models.CharField(max_length=255)),
                ('Ctc', models.PositiveIntegerField(blank=True, null=True)),
                ('Date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=250)),
                ('Password', models.CharField(max_length=250)),
                ('Confirm_Password', models.CharField(max_length=250)),
            ],
        ),
    ]
